# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/bennett/.oh-my-zsh"

export GPG_TTY=$(tty)

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="benoster"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Aliases
# Utilities
alias batt="upower -i /org/freedesktop/UPower/devices/battery_BAT1"
alias zip="zip -r"
alias space="sudo ncdu -x"

# Terminal Navigation
alias ls="exa --icons -g --color=always --group-directories-first"
alias la="exa --icons -ga --color=always --group-directories-first"
alias ll="exa --icons -gal --color=always --group-directories-first"
alias grep="grep --color=auto"
alias cp="cp -i"
alias cat="bat"
alias du="duf"
alias df="df -h"
alias ..="cd .."
alias ...="cd ../.."

#Git
alias dotfiles="/usr/bin/git --git-dir=/home/bennett/.dotfiles --work-tree=/home/bennett"

# Import colorscheme from 'wal' asynchronously
# & means run the process in the background
# () mean to run the process in a subshell to eliminate output
#( \cat ~/.cache/wal/sequences & )

# Set up rbenv for multiple Ruby versions
eval "$(rbenv init -)"

# Set up pyenv to work in the shell
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# This command acts as a greeting
fortune -a computers
